export const SET_ALERT = "SET_ALERT";
export const SET_SIGNIN_ALERT = "SET_SIGNIN_ALERT";
export const SET_SIGNUP_ALERT = "SET_SIGNUP_ALERT";
export const REMOVE_SIGNIN_ALERT = "REMOVE_SIGNIN_ALERT";
export const REMOVE_SIGNUP_ALERT = "REMOVE_SIGNUP_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
